[package]
name = "rustracer"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Curry (andrew.d.curry@gmail.com)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec3D = "0.3.0"
linspacers = "0.1.1"